### ISSUE TITLE
[Request,Bug] video player is missing some basic functionality

### ISSUE THREAD

**Issue by DexterEnigma** [RyanYuuki/AnymeX#10]
The video player in the app is missing some key things like separate Brightness and volume control. Also double tap to seek would be ideal. I also noticed a weird bug that the screen tries to turn off while watching.

**Comment by RyanYuuki** [comment]
@DexterEnigma Oh come on, does anilab have volume control and brightness control😭 and its hell of a lot popular app then mine.

**Comment by RyanYuuki** [comment]
I'll be adding it in the next update.

**Comment by DexterEnigma** [comment]
Thank you

**Comment by RyanYuuki** [comment]
@DexterEnigma Make sure you are on the latest version, because the player sleeping while watching is already fixed.

**Comment by RyanYuuki** [comment]
Fixed most of the bugs, now supports double tap seek.
