### ISSUE TITLE
[Request] Can you please add Material You App icon 

### ISSUE THREAD

**Issue by MysticPalash** [RyanYuuki/AnymeX#3]
It would be good if this app has Material You (Themed ) App  icon. So that it can match colour scheme of other app icons.It is very Good app btw.

**Comment by RyanYuuki** [comment]
> It would be good if this app has Material You (Themed ) App icon. So that it can match colour scheme of other app icons.It is very Good app btw.

thanks a lot for an amazing feedback and yeah i will add material icons asap

**Comment by MysticPalash** [comment]
Thank You ❤️

**Comment by MysticPalash** [comment]
Added in V2.8.0

**Comment by RyanYuuki** [comment]
@ChAJ07 no actually only the title appeared in my telegram channel so I thought u was asking for me to add support when I already did hence the reply "bruh" 😭

**Comment by MysticPalash** [comment]
Closed it because You forgot to close it. ig🤣😂
