### ISSUE TITLE
Api based site's 

### ISSUE THREAD

**Issue by OshekharO** [RyanYuuki/AnymeX#39]
### Feature Summary

https://kisskh.co
https://mystorywave.com
https://wtr-lab.com
https://www.novelcool.com/

### Submission Checklist

- [X] I have searched the existing issues and confirm that this feature has not been requested before.
- [X] I have provided a clear and descriptive title.
- [X] I am using the **[latest](https://github.com/RyanYuuki/AnymeX/releases/latest)** version of AnymeX. If not, I have provided a reason for using an older version.
- [X] I understand that not all feature requests will be accepted, and if declined, I won't resubmit the same request.

**Comment by itsmechinmoy** [comment]
Dev will shift to mangayomi extensions 
So no more inbuilt extensions
