### ISSUE TITLE
The animation doesn't play.

### ISSUE THREAD

**Issue by tagjg** [RyanYuuki/AnymeX#40]
### Steps to Reproduce

1. Set Source to either HiAnime(Scrapper) or HiAnime(API).
2. Play the anime.

### Expected Outcome

Animation should play normally even if the source is Hianime.

### Actual Outcome

The animation doesn't play.
The loading mark is displayed all the time.

### AnymeX Version

AnymeX-iOS-v2.8.4-2.ipa

### Operating System Version

ios Version：18.0

### Device Information

iPad 9

### Additional Information

The app is running on a LiveContainer.

### Submission Checklist

- [X] I have searched existing issues to confirm this is not a duplicate.
- [X] I have provided a clear and descriptive title.
- [X] I am using the **[latest](https://github.com/RyanYuuki/AnymeX/releases/latest)** version of AnymeX. If not, I have provided a reason for not updating.
- [X] I have updated all relevant extensions or dependencies.
- [X] I have filled out all the requested information accurately.

**Comment by itsmechinmoy** [comment]
What animation? Send screen recording

**Comment by ghost** [comment]
If I select source as HiAnime, it won't play any anime.

https://github.com/user-attachments/assets/da74d20f-7176-48a1-b377-bdf9f2099f6c

**Comment by itsmechinmoy** [comment]
Hianime extension is broken, and also the dev will shift to mangayomi extensions so we won't maintain them anymore

**Comment by itsmechinmoy** [comment]
@itsmechinmoy test
