### ISSUE TITLE
Video player needs some fixes

### ISSUE THREAD

**Issue by ExZyk** [RyanYuuki/AnymeX#41]
### Steps to Reproduce

Double tap to seek isn't working.

### Expected Outcome

Before the update it's working just fine.

### Actual Outcome

I double tap and nothing happened.

### AnymeX Version

v2.8.5-alpha

### Operating System Version

Android 15

### Device Information

Google Pixel 6

### Additional Information

Video player needs some improvement because I can't double tap to seek and the volume/brightness control is too sensitive. Make it like you have to tap it first to control it 

### Submission Checklist

- [X] I have searched existing issues to confirm this is not a duplicate.
- [X] I have provided a clear and descriptive title.
- [X] I am using the **[latest](https://github.com/RyanYuuki/AnymeX/releases/latest)** version of AnymeX. If not, I have provided a reason for not updating.
- [X] I have updated all relevant extensions or dependencies.
- [X] I have filled out all the requested information accurately.

**Comment by itsmechinmoy** [comment]
Do not create issues if your alpha app isn't working as expected. Join our discord server for that
