### ISSUE TITLE
Anime not downloading

### ISSUE THREAD

**Issue by soli11593** [RyanYuuki/AnymeX#42]
### Steps to Reproduce

When I am trying to download an episode from animephae server the download starts gets completed 98 percent and then it vanishes and the downloaded video is not inside downloads tab

### Expected Outcome

Downloaded video

### Actual Outcome

No video

### AnymeX Version

2.8.5

### Operating System Version

Android 14

### Device Information

OnePlus nord 3

### Submission Checklist

- [X] I have searched existing issues to confirm this is not a duplicate.
- [X] I have provided a clear and descriptive title.
- [X] I am using the **[latest](https://github.com/RyanYuuki/AnymeX/releases/latest)** version of AnymeX. If not, I have provided a reason for not updating.
- [X] I have updated all relevant extensions or dependencies.
- [X] I have filled out all the requested information accurately.

**Comment by itsmechinmoy** [comment]
Do not create issues if your alpha app isn't working as expected. Join our discord server for that.
Also we don't provide support for extensions.
