### ISSUE TITLE
[Bug] Auto Theme Doesn't work

### ISSUE THREAD

**Issue by DexterEnigma** [RyanYuuki/AnymeX#9]
Auto Theming in the theme settings doesn't seems to work. It goes back to dark even if the system isn't dark yet. It doesn't seems to respect system theme.

**Comment by RyanYuuki** [comment]
That's very weird, guess it was like that from the start. I never noticed it, I'll fix it asap.

**Comment by DexterEnigma** [comment]
> That's very weird, guess it was like that from the start. I never noticed it, I'll fix it asap.

Yeah it was. I thought you will notice and fix eventually. I see its still not fixed?

**Comment by RyanYuuki** [comment]
Forgot about it, it's fixed now on latest version.
